spring.application.name=Sla_Reuniao

# ===============================
# CONFIGURA��O DO POSTGRESQL REAL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/reuniao_db
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURA��ES DO HIBERNATE (ORM)
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURA��ES DO MOTOR DE E-MAIL (GMAIL)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedreirosdesoftware09@gmail.com
spring.mail.password=hwfulzfmypfpppom
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com